# Generated by Django 4.2.5 on 2024-01-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyuzbekistanapp', '0002_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
